name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout testes Playwright
        uses: actions/checkout@v4

      - name: Checkout Acolhe
        uses: actions/checkout@v4
        with:
          repository: isapaula/Psychology-clinic-project
          path: acolhe

      - name: Subir aplicação Acolhe
        run: docker compose -f acolhe/docker-compose.yml up -d --build

      - name: Verificar containers
        run: docker compose -f acolhe/docker-compose.yml ps

      - name: Aguardar aplicação
        run: |
          for i in {1..30}; do
            if curl --fail http://localhost:8080/; then
              echo "Aplicação disponível!"
              exit 0
            fi

            echo "Aguardando aplicação..."
            sleep 2
          done

          echo "Aplicação não ficou disponível."
          docker compose -f acolhe/docker-compose.yml logs
          exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Derrubar aplicação
        if: always()
        run: docker compose -f acolhe/docker-compose.yml down