name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout testes Playwright
        uses: actions/checkout@v4

      - name: Checkout projeto principal
        uses: actions/checkout@v4
        with:
          repository: isapaula/Psychology-clinic-project
          path: app

      - name: Verificar estrutura
        run: |
          echo "=== Diretório atual ==="
          pwd

          echo "=== Arquivos do projeto principal ==="
          ls -la app

          echo "=== Docker Compose ==="
          cat app/docker-compose.yaml

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test